"""Mapowanie stref → templates/page.losuj-produkt.json."""

from __future__ import annotations

from Komponenty._shared.theme_page_editor.types import TemplateField, TemplateZone, _s


PAGE_ZONES: tuple[TemplateZone, ...] = (
    TemplateZone(
        zone_id="random_artwork",
        label="Losuj obraz — interfejs",
        description="Teksty sekcji giclee-random-artwork (Fine Art Oracle).",
        section_key="random_artwork",
        fields=(
            TemplateField("eyebrow", "Nadtytuł", "text", _s("random_artwork", "settings", "eyebrow")),
            TemplateField("heading", "Nagłówek", "text", _s("random_artwork", "settings", "heading")),
            TemplateField("subtitle", "Podtytuł", "text", _s("random_artwork", "settings", "subtitle")),
            TemplateField("button_label", "Przycisk losowania", "text", _s("random_artwork", "settings", "button_label")),
            TemplateField("loading_text", "Tekst ładowania", "text", _s("random_artwork", "settings", "loading_text")),
            TemplateField("result_heading", "Nagłówek wyniku", "text", _s("random_artwork", "settings", "result_heading")),
            TemplateField("view_label", "Przycisk «Zobacz»", "text", _s("random_artwork", "settings", "view_label")),
            TemplateField("replay_label", "Przycisk «Losuj ponownie»", "text", _s("random_artwork", "settings", "replay_label")),
            TemplateField("error_text", "Komunikat błędu", "text", _s("random_artwork", "settings", "error_text")),
            TemplateField("retry_label", "Przycisk ponowienia", "text", _s("random_artwork", "settings", "retry_label")),
            TemplateField("pool_limit", "Limit puli produktów", "int", _s("random_artwork", "settings", "pool_limit")),
            TemplateField("fetch_full_pool", "Pobierz pełną pulę kolekcji", "bool", _s("random_artwork", "settings", "fetch_full_pool")),
            TemplateField(
                "background_image",
                "Własne tło — obraz",
                "shopify_image",
                _s("random_artwork", "settings", "background_image"),
                hint="Puste = domyślna scena (aurora + WebGL).",
            ),
            TemplateField(
                "background_video",
                "Własne tło — film / animacja",
                "shopify_video",
                _s("random_artwork", "settings", "background_video"),
                hint="Film ma pierwszeństwo przed obrazem. MP4/WebM/MOV lub ref Shopify.",
            ),
            TemplateField(
                "background_parallax",
                "Parallax tła (mysz)",
                "bool",
                _s("random_artwork", "settings", "background_parallax"),
                hint="Subtelny ruch obrazu lub filmu przy ruszaniu kursorem.",
            ),
        ),
    ),
    TemplateZone(
        zone_id="random_artwork_atmosphere",
        label="Edytuj atmosferę…",
        description=(
            "V1 zachowuje wartości bez ładowania warstwy. V2 używa parametrów glow, "
            "mgiełki i pyłu. V3–V5 używają reflektora i zoptymalizowanego pyłu Living Museum Light."
        ),
        section_key="random_artwork",
        settings_only=True,
        fields=(
            TemplateField("atmosphere_intensity", "V2 — glow: intensywność (%)", "int", _s("random_artwork", "settings", "atmosphere_intensity"), hint="0–70. Domyślnie 35."),
            TemplateField("atmosphere_glow_size", "V2 — glow: rozmiar (%)", "int", _s("random_artwork", "settings", "atmosphere_glow_size"), hint="60–160. Domyślnie 100."),
            TemplateField("atmosphere_glow_response", "V2 — glow: responsywność (%)", "int", _s("random_artwork", "settings", "atmosphere_glow_response"), hint="10–100. Domyślnie 50."),
            TemplateField("atmosphere_haze", "V2 — mgiełka: intensywność (%)", "int", _s("random_artwork", "settings", "atmosphere_haze"), hint="0–100. Domyślnie 100."),
            TemplateField("atmosphere_haze_speed", "V2 — mgiełka: szybkość (%)", "int", _s("random_artwork", "settings", "atmosphere_haze_speed"), hint="0–200. 0 zatrzymuje ruch."),
            TemplateField("atmosphere_dust", "V2 — pył: widoczność (%)", "int", _s("random_artwork", "settings", "atmosphere_dust"), hint="0–60. Domyślnie 25."),
            TemplateField("atmosphere_dust_amount", "V2 — pył: ilość (%)", "int", _s("random_artwork", "settings", "atmosphere_dust_amount"), hint="0–100. Domyślnie 50."),
            TemplateField("atmosphere_dust_speed", "V2 — pył: szybkość (%)", "int", _s("random_artwork", "settings", "atmosphere_dust_speed"), hint="0–200. 0 zatrzymuje ruch."),
            TemplateField(
                "living_light_enabled",
                "V3 — włącz reflektor kursora",
                "bool",
                _s("random_artwork", "settings", "living_light_enabled"),
                hint="Wyłącza reflektor bez zmiany portalu ani WebGL.",
            ),
            TemplateField(
                "living_dust_enabled",
                "V3 — włącz pył ambientowy",
                "bool",
                _s("random_artwork", "settings", "living_dust_enabled"),
                hint="Pył 2D wygasa podczas właściwej animacji WebGL.",
            ),
            TemplateField(
                "living_light_intensity",
                "V3 — intensywność światła (%)",
                "int",
                _s("random_artwork", "settings", "living_light_intensity"),
                hint="0–100. Domyślnie 45.",
            ),
            TemplateField(
                "living_dust_particles",
                "V3 — pył: liczba drobinek",
                "int",
                _s("random_artwork", "settings", "living_dust_particles"),
                hint="20–240. Domyślnie 120.",
            ),
            TemplateField(
                "living_dust_opacity",
                "V3 — pył: widoczność (%)",
                "int",
                _s("random_artwork", "settings", "living_dust_opacity"),
                hint="0–200. Domyślnie 115.",
            ),
            TemplateField(
                "living_dust_size",
                "V3 — pył: rozmiar (%)",
                "int",
                _s("random_artwork", "settings", "living_dust_size"),
                hint="50–200. Domyślnie 125.",
            ),
            TemplateField(
                "living_dust_speed",
                "V3 — pył: szybkość (%)",
                "int",
                _s("random_artwork", "settings", "living_dust_speed"),
                hint="0–200. Domyślnie 75.",
            ),
            TemplateField(
                "living_dust_fps",
                "V3 — pył: limit FPS",
                "int",
                _s("random_artwork", "settings", "living_dust_fps"),
                hint="12–30. Domyślnie 24.",
            ),
            TemplateField(
                "living_dust_dpr_cap",
                "V3 — pył: limit jakości DPR (%)",
                "int",
                _s("random_artwork", "settings", "living_dust_dpr_cap"),
                hint="75–150. Domyślnie 125 = DPR 1.25.",
            ),
        ),
    ),
    TemplateZone(
        zone_id="random_artwork_v5_smoke",
        label="V5 — włącz/wyłącz dym",
        description=(
            "Efekt Elegant Fluid WebGL przeniesiony z Pedzel Alchemy, wariant 2. "
            "Ustawienie jest domyślnie włączone tylko w wariancie V5."
        ),
        section_key="random_artwork",
        settings_only=True,
        fields=(
            TemplateField(
                "cursor_smoke_enabled",
                "Włącz efekt dymu kursora",
                "bool",
                _s("random_artwork", "settings", "cursor_smoke_enabled"),
                hint="Włącza stonowany fluid w kolorach teal, lila, champagne i ash.",
            ),
        ),
    ),
    TemplateZone(
        zone_id="random_artwork_v5_smoke_parameters",
        label="V5 — edytuj dym kursora",
        description=(
            "Preset ustala bazowy charakter symulacji. Suwaki procentowe modyfikują preset, "
            "więc 100% zachowuje jego wartości wzorcowe."
        ),
        section_key="random_artwork",
        settings_only=True,
        fields=(
            TemplateField(
                "cursor_smoke_preset",
                "Preset dymu",
                "choice",
                _s("random_artwork", "settings", "cursor_smoke_preset"),
                hint="Elegant V2 jest wiernym wariantem źródłowym. Pozostałe presety zmieniają tempo, paletę i charakter smugi.",
                choices=(
                    ("elegant", "Elegant V2 — oryginalny"),
                    ("gallery_mist", "Gallery Mist — miękka mgła"),
                    ("silk", "Silk — dłuższe jedwabne smugi"),
                    ("whisper", "Whisper — prawie niewidoczny"),
                ),
            ),
            TemplateField(
                "cursor_smoke_quality",
                "Jakość symulacji",
                "choice",
                _s("random_artwork", "settings", "cursor_smoke_quality"),
                hint="Standard jest zalecany. Niska oszczędza GPU; wysoka zwiększa szczegółowość dymu.",
                choices=(
                    ("low", "Niska — 512 px"),
                    ("standard", "Standard — 1024 px"),
                    ("high", "Wysoka — 1536 px"),
                ),
            ),
            TemplateField(
                "cursor_smoke_intensity",
                "Nasycenie koloru (%)",
                "int",
                _s("random_artwork", "settings", "cursor_smoke_intensity"),
                hint="25–200. Siła koloru wstrzykiwanego do symulacji; 100 = wartość presetu.",
                min_value=25,
                max_value=200,
                step=5,
            ),
            TemplateField(
                "cursor_smoke_opacity",
                "Krycie całej warstwy (%)",
                "int",
                _s("random_artwork", "settings", "cursor_smoke_opacity"),
                hint="20–150. Widoczność canvasa nad tłem; 100 = wartość presetu.",
                min_value=20,
                max_value=150,
                step=5,
            ),
            TemplateField(
                "cursor_smoke_size",
                "Rozmiar smugi (%)",
                "int",
                _s("random_artwork", "settings", "cursor_smoke_size"),
                hint="50–200. Średnica dymu tworzonego bezpośrednio pod kursorem.",
                min_value=50,
                max_value=200,
                step=5,
            ),
            TemplateField(
                "cursor_smoke_force",
                "Siła ruchu (%)",
                "int",
                _s("random_artwork", "settings", "cursor_smoke_force"),
                hint="25–200. Jak mocno prędkość kursora porusza płynem.",
                min_value=25,
                max_value=200,
                step=5,
            ),
            TemplateField(
                "cursor_smoke_persistence",
                "Trwałość smugi (%)",
                "int",
                _s("random_artwork", "settings", "cursor_smoke_persistence"),
                hint="50–200. Wyższa wartość oznacza wolniejsze zanikanie dymu.",
                min_value=50,
                max_value=200,
                step=5,
            ),
            TemplateField(
                "cursor_smoke_swirl",
                "Wirowanie (%)",
                "int",
                _s("random_artwork", "settings", "cursor_smoke_swirl"),
                hint="0–200. Ilość zawijania i turbulentnego ruchu smugi.",
                min_value=0,
                max_value=200,
                step=5,
            ),
            TemplateField(
                "cursor_smoke_bloom",
                "Poświata i promienie (%)",
                "int",
                _s("random_artwork", "settings", "cursor_smoke_bloom"),
                hint="0–200. Wzmacnia bloom i delikatne sunrays; 0 całkowicie je wygasza.",
                min_value=0,
                max_value=200,
                step=5,
            ),
            TemplateField(
                "cursor_smoke_auto_enabled",
                "Automatyczne smugi w tle",
                "bool",
                _s("random_artwork", "settings", "cursor_smoke_auto_enabled"),
                hint="Dodaje pojedynczy, subtelny oddech dymu także bez ruchu kursora.",
            ),
            TemplateField(
                "cursor_smoke_auto_frequency",
                "Częstotliwość automatycznych smug (%)",
                "int",
                _s("random_artwork", "settings", "cursor_smoke_auto_frequency"),
                hint="25–200. 200% = dwa razy częściej, 50% = dwa razy rzadziej.",
                min_value=25,
                max_value=200,
                step=5,
            ),
        ),
    ),
)
