from __future__ import annotations

from Komponenty.stronaglowna import registry
from Komponenty.stronaglowna.prehero_integration import (
    PREHERO_ZONE_ID,
    apply_prehero_values,
    export_prehero_config,
    inject_prehero_into_snippet,
    load_prehero_values,
)


def test_prehero_zone_is_first_and_editable() -> None:
    assert registry.HOME_ZONES
    zone = registry.HOME_ZONES[0]
    assert zone.zone_id == PREHERO_ZONE_ID
    assert registry.HOME_ZONES[1].zone_id == "hero"
    assert [field.field_id for field in zone.fields] == [
        "prehero_enabled",
        "prehero_video",
        "prehero_scroll_screens",
        "prehero_reveal_screens",
        "prehero_hero_rise_screens",
        "prehero_copy_enabled",
        "prehero_copy_text",
        "prehero_horizontal_curtain_enabled",
        "prehero_hero_hold_screens",
        "prehero_horizontal_curtain_screens",
        "prehero_intro_hold_screens",
    ]


def test_prehero_settings_roundtrip_and_normalization() -> None:
    settings = {"current": {}}
    apply_prehero_values(
        settings,
        {
            "prehero_enabled": True,
            "prehero_video": "shopify://files/videos/prehero.mp4",
            "prehero_scroll_screens": 6,
            "prehero_reveal_screens": 2,
            "prehero_hero_rise_screens": 1,
            "prehero_copy_enabled": True,
            "prehero_copy_text": "Linia pierwsza\nLinia druga\nLinia trzecia",
            "prehero_horizontal_curtain_enabled": True,
            "prehero_hero_hold_screens": 1,
            "prehero_horizontal_curtain_screens": 1,
            "prehero_intro_hold_screens": 1,
        },
    )

    values = load_prehero_values(settings)
    config = export_prehero_config(settings)

    assert values["prehero_video"].endswith("prehero.mp4")
    assert config["scrollHeightVh"] == 600
    assert config["revealOverlapVh"] == 200
    assert config["heroRiseVh"] == 100
    assert config["copyLines"] == ["Linia pierwsza", "Linia druga", "Linia trzecia"]
    assert config["horizontalCurtainEnabled"] is True
    assert config["heroHoldVh"] == 100
    assert config["heroCurtainVh"] == 100
    assert config["introHoldVh"] == 100


def test_prehero_snippet_injection_is_idempotent() -> None:
    source = """{% comment %} auto-generated {% endcomment %}
<script>
window.GICLEE_HOME_SECTIONS = {"hero": "slideshow_4LMfx7"};
window.GICLEE_HOME_STACK = true;
</script>
<style>body { color: white; }</style>
"""
    config = {
        "enabled": True,
        "scrollHeightVh": 600,
        "revealOverlapVh": 200,
        "heroRiseVh": 100,
        "copyEnabled": True,
        "copyLines": ["A", "B", "C"],
        "horizontalCurtainEnabled": True,
        "heroHoldVh": 100,
        "heroCurtainVh": 100,
        "introHoldVh": 100,
        "videoRef": "shopify://files/videos/prehero.mp4",
    }

    first = inject_prehero_into_snippet(source, config)
    second = inject_prehero_into_snippet(first, config)

    assert first == second
    assert first.count("GICLEE_PREHERO_CONFIG_BEGIN") == 1
    assert first.count("GICLEE_PREHERO_ASSETS_BEGIN") == 1
    assert "window.GICLEE_PREHERO_CONFIG" in first
    assert '"heroHoldVh": 100' in first
    assert '"introHoldVh": 100' in first
    assert "'prehero.mp4' | file_url" in first
    assert "giclee-home-prehero-reveal.js" in first
    assert "giclee-home-hero-horizontal-curtain.css" in first
    assert "giclee-home-hero-horizontal-curtain.js" in first
    assert "giclee-home-intro-curtain-effects.js" in first
    assert first.index("GICLEE_PREHERO_CONFIG_BEGIN") < first.index("</script>")
    assert first.index("GICLEE_PREHERO_ASSETS_BEGIN") > first.index("</script>")


def test_prehero_is_not_injected_when_disabled_or_stack_is_disabled() -> None:
    stack_off = "{% comment %} auto-generated by write_home_assets: stack disabled {% endcomment %}\n"
    assert inject_prehero_into_snippet(stack_off) == stack_off

    stack_on = "<script>window.GICLEE_HOME_STACK = true;</script>\n"
    disabled = export_prehero_config({"current": {"prehero_enabled": False}})
    assert "GICLEE_PREHERO_ASSETS_BEGIN" not in inject_prehero_into_snippet(stack_on, disabled)
