#!/usr/bin/env python3
"""Build the pre-Hero MP4 into a bounded WebP frame sequence.

The output is intentionally flat inside ``assets/`` because Shopify themes don't
support arbitrary asset subdirectories. A Liquid manifest with CDN URLs is
written to ``snippets/giclee-home-prehero-frame-manifest.liquid``.
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = ROOT / "assets" / "giclee-home-prehero-scrub.mp4"
ASSETS_DIR = ROOT / "assets"
MANIFEST_PATH = ROOT / "snippets" / "giclee-home-prehero-frame-manifest.liquid"
FRAME_PREFIX = "giclee-prehero-frame-"
FRAME_GLOB = f"{FRAME_PREFIX}*.webp"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--fps", type=float, default=20.0)
    parser.add_argument("--width", type=int, default=1600)
    parser.add_argument("--quality", type=int, default=72)
    parser.add_argument("--cache-size", type=int, default=18)
    parser.add_argument("--preload-radius", type=int, default=4)
    parser.add_argument("--max-dpr", type=float, default=1.5)
    parser.add_argument(
        "--budget-mb",
        type=float,
        default=24.0,
        help="Abort before replacing existing frames when the generated sequence exceeds this size.",
    )
    return parser.parse_args()


def require_binary(name: str) -> str:
    resolved = shutil.which(name)
    if not resolved:
        raise RuntimeError(
            f"Brak programu {name}. Zainstaluj FFmpeg i upewnij się, że {name} jest dostępny w PATH."
        )
    return resolved


def run(command: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        command,
        check=True,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )


def probe_video(ffprobe: str, source: Path) -> dict[str, Any]:
    result = run(
        [
            ffprobe,
            "-v",
            "error",
            "-select_streams",
            "v:0",
            "-show_entries",
            "stream=width,height,duration,r_frame_rate:format=duration",
            "-of",
            "json",
            str(source),
        ]
    )
    payload = json.loads(result.stdout)
    streams = payload.get("streams") or []
    stream = streams[0] if streams else {}
    format_data = payload.get("format") or {}
    duration_raw = stream.get("duration") or format_data.get("duration") or 0
    duration = float(duration_raw)
    if duration <= 0:
        raise RuntimeError("Nie udało się odczytać długości źródłowego filmu.")
    return {
        "duration": duration,
        "width": int(stream.get("width") or 0),
        "height": int(stream.get("height") or 0),
        "source_fps": str(stream.get("r_frame_rate") or ""),
    }


def build_frames(
    ffmpeg: str,
    source: Path,
    target_dir: Path,
    *,
    fps: float,
    width: int,
    quality: int,
) -> list[Path]:
    pattern = target_dir / f"{FRAME_PREFIX}%04d.webp"
    filter_chain = f"fps={fps:g},scale='min({width},iw)':-2:flags=lanczos"
    run(
        [
            ffmpeg,
            "-hide_banner",
            "-loglevel",
            "error",
            "-y",
            "-i",
            str(source),
            "-an",
            "-vf",
            filter_chain,
            "-c:v",
            "libwebp",
            "-quality",
            str(quality),
            "-compression_level",
            "6",
            "-preset",
            "picture",
            str(pattern),
        ]
    )
    return sorted(target_dir.glob(FRAME_GLOB))


def liquid_manifest(
    frame_names: list[str],
    *,
    duration: float,
    fps: float,
    cache_size: int,
    preload_radius: int,
    max_dpr: float,
    total_bytes: int,
) -> str:
    url_lines = [
        "    {{ '" + name.replace("'", "\\'") + "' | asset_url | json }}"
        for name in frame_names
    ]
    urls = ",\n".join(url_lines)
    return (
        "{% comment %}\n"
        "  Auto-generated by scripts/build_prehero_webp_sequence.py.\n"
        f"  Frames: {len(frame_names)}, total bytes: {total_bytes}.\n"
        "{% endcomment %}\n"
        "window.GICLEE_PREHERO_FRAME_SEQUENCE = {\n"
        "  enabled: true,\n"
        "  format: 'webp',\n"
        f"  frameCount: {len(frame_names)},\n"
        f"  duration: {duration:.6f},\n"
        f"  sourceFps: {fps:g},\n"
        f"  cacheSize: {cache_size},\n"
        f"  preloadRadius: {preload_radius},\n"
        f"  maxDpr: {max_dpr:g},\n"
        "  urls: [\n"
        f"{urls}\n"
        "  ]\n"
        "};\n"
    )


def main() -> int:
    args = parse_args()
    source = args.input.expanduser().resolve()
    if not source.is_file():
        raise RuntimeError(f"Nie znaleziono filmu źródłowego: {source}")
    if not 8 <= args.fps <= 30:
        raise RuntimeError("--fps musi mieścić się w zakresie 8–30.")
    if not 640 <= args.width <= 2560:
        raise RuntimeError("--width musi mieścić się w zakresie 640–2560.")
    if not 1 <= args.quality <= 100:
        raise RuntimeError("--quality musi mieścić się w zakresie 1–100.")

    ffmpeg = require_binary("ffmpeg")
    ffprobe = require_binary("ffprobe")
    metadata = probe_video(ffprobe, source)

    with tempfile.TemporaryDirectory(prefix="giclee-prehero-frames-") as temp_name:
        temp_dir = Path(temp_name)
        frames = build_frames(
            ffmpeg,
            source,
            temp_dir,
            fps=args.fps,
            width=args.width,
            quality=args.quality,
        )
        if len(frames) < 2:
            raise RuntimeError("FFmpeg nie wygenerował poprawnej sekwencji klatek.")

        total_bytes = sum(path.stat().st_size for path in frames)
        budget_bytes = int(args.budget_mb * 1024 * 1024)
        if total_bytes > budget_bytes:
            raise RuntimeError(
                "Sekwencja przekracza budżet "
                f"{args.budget_mb:.1f} MB: {total_bytes / 1024 / 1024:.1f} MB. "
                "Zmniejsz --width, --quality albo --fps."
            )

        ASSETS_DIR.mkdir(parents=True, exist_ok=True)
        MANIFEST_PATH.parent.mkdir(parents=True, exist_ok=True)

        for old in ASSETS_DIR.glob(FRAME_GLOB):
            old.unlink()

        moved_names: list[str] = []
        for frame in frames:
            target = ASSETS_DIR / frame.name
            shutil.move(str(frame), str(target))
            moved_names.append(target.name)

        MANIFEST_PATH.write_text(
            liquid_manifest(
                moved_names,
                duration=float(metadata["duration"]),
                fps=args.fps,
                cache_size=max(8, min(36, args.cache_size)),
                preload_radius=max(2, min(10, args.preload_radius)),
                max_dpr=max(1.0, min(2.0, args.max_dpr)),
                total_bytes=total_bytes,
            ),
            encoding="utf-8",
        )

    print("GICLÉE pre-Hero WebP sequence ready")
    print(f"source: {source}")
    print(f"duration: {metadata['duration']:.3f}s")
    print(f"frames: {len(moved_names)} at {args.fps:g} FPS")
    print(f"size: {total_bytes / 1024 / 1024:.2f} MB")
    print(f"manifest: {MANIFEST_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except subprocess.CalledProcessError as error:
        detail = (error.stderr or error.stdout or str(error)).strip()
        print(f"Błąd FFmpeg: {detail}", file=sys.stderr)
        raise SystemExit(2)
    except RuntimeError as error:
        print(str(error), file=sys.stderr)
        raise SystemExit(2)
